export const products = [
  {
    id: 10,
    name: "Vintage T-shirts",
    imageUrl: "/images/product1.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Furnitures",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-10",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 20,
    name: "Quality Loafers",
    imageUrl: "/images/product2.png",
    amount: 15600,
    originalAmount: 5000,
    category: "Phones",
    brandName: "Android",
    slug: "Quality-Loafers-20",
    seller: "Blessed kiosk",
    quantity: 9,
    shippingFee: 2000,
  },
  {
    id: 30,
    name: "Vintage T-shirts",
    imageUrl: "/images/product3.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Laptops",
    brandName: "Androidhshshhshshshshs",
    slug: "Vintage-T-shirts-30",
    seller: "Gucci store",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 40,
    name: "Vintage T-shirts",
    imageUrl: "/images/product4.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Fashion",
    brandName: "Apple",
    slug: "Vintage-T-shirts-40",
    seller: "Indie hub",
    quantity: 59,
    shippingFee: 3000,
  },
  {
    id: 50,
    name: "Vintage T-shirts",
    imageUrl: "/images/product5.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Baby & toys",
    brandName: "LG",
    slug: "Vintage-T-shirts-50",
    seller: "Blessed",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 60,
    name: "Vintage T-shirts",
    imageUrl: "/images/product6.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Gaming",
    brandName: "Samsung",
    slug: "Vintage-T-shirts-60",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 70,
    name: "Vintage T-shirts",
    imageUrl: "/images/product7.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Sports and Fitness",
    brandName: "Infinix",
    slug: "Vintage-T-shirts-70",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 80,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 5500,
    originalAmount: 10000,
    category: "Home & Office",
    brandName: "Tecno",
    slug: "Vintage-T-shirts-80",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 90,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 8500,
    originalAmount: 20000,
    category: "Health & Office",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-90",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 100,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 10500,
    originalAmount: 30000,
    category: "Health & Beauty",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-100",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 2000,
  },
  {
    id: 110,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 50500,
    originalAmount: 40000,
    category: "SuperMarkets",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-110",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 120,
    name: "Vintage T-shirts",
    imageUrl: "/images/product1.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Furnitures",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-120",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 2000,
  },
  {
    id: 130,
    name: "Quality Loafers",
    imageUrl: "/images/product2.png",
    amount: 15600,
    originalAmount: 5000,
    category: "Phones",
    brandName: "Android",
    slug: "Quality-Loafers-130",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 140,
    name: "Vintage T-shirts",
    imageUrl: "/images/product3.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Laptops",
    brandName: "Androidhshshhshshshshs",
    slug: "Vintage-T-shirts-140",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 150,
    name: "Vintage T-shirts",
    imageUrl: "/images/product4.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Fashion",
    brandName: "Apple",
    slug: "Vintage-T-shirts-150",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 160,
    name: "Vintage T-shirts",
    imageUrl: "/images/product5.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Baby & toys",
    brandName: "LG",
    slug: "Vintage-T-shirts-160",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 170,
    name: "Vintage T-shirts",
    imageUrl: "/images/product6.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Gaming",
    brandName: "Samsung",
    slug: "Vintage-T-shirts-170",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 180,
    name: "Vintage T-shirts",
    imageUrl: "/images/product7.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Sports and Fitness",
    brandName: "Infinix",
    slug: "Vintage-T-shirts-180",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 190,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 5500,
    originalAmount: 10000,
    category: "Home & Office",
    brandName: "Tecno",
    slug: "Vintage-T-shirts-190",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 200,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 8500,
    originalAmount: 20000,
    category: "Health & Office",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-200",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 210,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 10500,
    originalAmount: 30000,
    category: "Health & Beauty",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-210",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 220,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 50500,
    originalAmount: 40000,
    category: "SuperMarkets",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-220",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },

  {
    id: 230,
    name: "Vintage T-shirts",
    imageUrl: "/images/product1.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Furnitures",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-230",
    seller: "Blessed Stores",
    quantity: 19,
    shippingFee: 2000,
  },
  {
    id: 240,
    name: "Quality Loafers",
    imageUrl: "/images/product2.png",
    amount: 15600,
    originalAmount: 5000,
    category: "Phones",
    brandName: "Android",
    slug: "Quality-Loafers-240",
    seller: "Blessed Stores",
    quantity: 5,
    shippingFee: 1000,
  },
  {
    id: 250,
    name: "Vintage T-shirts",
    imageUrl: "/images/product3.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Laptops",
    brandName: "Androidhshshhshshshshs",
    slug: "Vintage-T-shirts-250",
    seller: "Blessed Stores",
    quantity: 4,
    shippingFee: 1000,
  },
  {
    id: 260,
    name: "Vintage T-shirts",
    imageUrl: "/images/product4.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Fashion",
    brandName: "Apple",
    slug: "Vintage-T-shirts-260",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 270,
    name: "Vintage T-shirts",
    imageUrl: "/images/product5.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Baby & toys",
    brandName: "LG",
    slug: "Vintage-T-shirts-270",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 280,
    name: "Vintage T-shirts",
    imageUrl: "/images/product6.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Gaming",
    brandName: "Samsung",
    slug: "Vintage-T-shirts-280",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 290,
    name: "Vintage T-shirts",
    imageUrl: "/images/product7.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Sports and Fitness",
    brandName: "Infinix",
    slug: "Vintage-T-shirts-290",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 300,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 5500,
    originalAmount: 10000,
    category: "Home & Office",
    brandName: "Tecno",
    slug: "Vintage-T-shirts-300",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 310,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 8500,
    originalAmount: 20000,
    category: "Health & Office",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-310",
    seller: "Blessed Stores",
    quantity: 2,
    shippingFee: 1000,
  },
  {
    id: 320,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 10500,
    originalAmount: 30000,
    category: "Health & Beauty",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-320",
    seller: "Blessed Stores",
    quantity: 39,
    shippingFee: 1000,
  },
  {
    id: 330,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 50500,
    originalAmount: 40000,
    category: "SuperMarkets",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-330",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 340,
    name: "Vintage T-shirts",
    imageUrl: "/images/product1.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Furnitures",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-340",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 350,
    name: "Quality Loafers",
    imageUrl: "/images/product2.png",
    amount: 15600,
    originalAmount: 5000,
    category: "Phones",
    brandName: "Android",
    slug: "Vintage-T-shirts-350",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 360,
    name: "Vintage T-shirts",
    imageUrl: "/images/product3.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Laptops",
    brandName: "Androidhshshhshshshshs",
    slug: "Vintage-T-shirts-360",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 370,
    name: "Vintage T-shirts",
    imageUrl: "/images/product4.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Fashion",
    brandName: "Apple",
    slug: "Vintage-T-shirts-370",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 380,
    name: "Vintage T-shirts",
    imageUrl: "/images/product5.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Baby & toys",
    brandName: "LG",
    slug: "Vintage-T-shirts-380",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 390,
    name: "Vintage T-shirts",
    imageUrl: "/images/product6.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Gaming",
    brandName: "Samsung",
    slug: "Vintage-T-shirts-390",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 400,
    name: "Vintage T-shirts",
    imageUrl: "/images/product7.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Sports and Fitness",
    brandName: "Infinix",
    slug: "Vintage-T-shirts-400",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 4000,
  },
  {
    id: 410,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 5500,
    originalAmount: 10000,
    category: "Home & Office",
    brandName: "Tecno",
    slug: "Vintage-T-shirts-410",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 2000,
  },
  {
    id: 420,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 8500,
    originalAmount: 20000,
    category: "Health & Office",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-420",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 430,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 10500,
    originalAmount: 30000,
    category: "Health & Beauty",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-430",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 440,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 50500,
    originalAmount: 40000,
    category: "SuperMarkets",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-440",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 450,
    name: "Vintage T-shirts",
    imageUrl: "/images/product1.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Furnitures",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-450",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 460,
    name: "Quality Loafers",
    imageUrl: "/images/product2.png",
    amount: 15600,
    originalAmount: 5000,
    category: "Phones",
    brandName: "Android",
    slug: "Quality-Loafers-460",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 470,
    name: "Vintage T-shirts",
    imageUrl: "/images/product3.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Laptops",
    brandName: "Androidhshshhshshshshs",
    slug: "Vintage-T-shirts-470",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 480,
    name: "Vintage T-shirts",
    imageUrl: "/images/product4.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Fashion",
    brandName: "Apple",
    slug: "Vintage-T-shirts-480",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 490,
    name: "Vintage T-shirts",
    imageUrl: "/images/product5.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Baby & toys",
    brandName: "LG",
    slug: "Vintage-T-shirts-490",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 500,
    name: "Vintage T-shirts",
    imageUrl: "/images/product6.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Gaming",
    brandName: "Samsung",
    slug: "Vintage-T-shirts-500",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 510,
    name: "Vintage T-shirts",
    imageUrl: "/images/product7.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Sports and Fitness",
    brandName: "Infinix",
    slug: "Vintage-T-shirts-510",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 520,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 5500,
    originalAmount: 10000,
    category: "Home & Office",
    brandName: "Tecno",
    slug: "Vintage-T-shirts-520",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 530,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 8500,
    originalAmount: 20000,
    category: "Health & Office",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-530",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 540,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 10500,
    originalAmount: 30000,
    category: "Health & Beauty",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-540",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 550,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 50500,
    originalAmount: 40000,
    category: "SuperMarkets",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-550",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },

  {
    id: 560,
    name: "Vintage T-shirts",
    imageUrl: "/images/product1.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Furnitures",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-560",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 570,
    name: "Quality Loafers",
    imageUrl: "/images/product2.png",
    amount: 15600,
    originalAmount: 5000,
    category: "Phones",
    brandName: "Android",
    slug: "Quality-Loafers-570",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 580,
    name: "Vintage T-shirts",
    imageUrl: "/images/product3.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Laptops",
    brandName: "Androidhshshhshshshshs",
    slug: "Vintage-T-shirts-580",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 590,
    name: "Vintage T-shirts",
    imageUrl: "/images/product4.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Fashion",
    brandName: "Apple",
    slug: "Vintage-T-shirts-590",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 600,
    name: "Vintage T-shirts",
    imageUrl: "/images/product5.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Baby & toys",
    brandName: "LG",
    slug: "Vintage-T-shirts-600",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 610,
    name: "Vintage T-shirts",
    imageUrl: "/images/product6.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Gaming",
    brandName: "Samsung",
    slug: "Vintage-T-shirts-610",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 620,
    name: "Vintage T-shirts",
    imageUrl: "/images/product7.png",
    amount: 5500,
    originalAmount: 5000,
    category: "Sports and Fitness",
    brandName: "Infinix",
    slug: "Vintage-T-shirts-620",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 630,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 5500,
    originalAmount: 10000,
    category: "Home & Office",
    brandName: "Tecno",
    slug: "Vintage-T-shirts-630",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1000,
  },
  {
    id: 640,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 8500,
    originalAmount: 20000,
    category: "Health & Office",
    brandName: "Binatone",
    slug: "Vintage-T-shirts-640",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1400,
  },
  {
    id: 650,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 10500,
    originalAmount: 30000,
    category: "Health & Beauty",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-650",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1500,
  },
  {
    id: 660,
    name: "Vintage T-shirts",
    imageUrl: "/images/Rectangle-7.png",
    amount: 50500,
    originalAmount: 40000,
    category: "SuperMarkets",
    brandName: "Gucci",
    slug: "Vintage-T-shirts-660",
    seller: "Blessed Stores",
    quantity: 10,
    shippingFee: 1310,
  },
];

// export const products = [
//   {
//     id: 10,
//     name: "Vintage T-shirts",
//     amount: 5500,
//     originalAmount: 5000,
//     category: "Furnitures",
//     brandName: "Binatone",
//     slug: "Vintage-T-shirts-10",
//     images: [
//       "/images/product1.png",
//       "/images/product2.png",
//       "/images/orderImage.png",
//       "/images/product5.png",
//     ],
//     seller: "Best Deals Electronics",
//     count: 1,
//     quantity: 5,
//     productDetails: [
//       {
//         descriptionHeader: "Product description",
//         descriptionContents:
//           "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus quam deserunt omnis atque maxime veniam, doloremque soluta libero, inventore possimus velit maiores porro error temporibus dolorem? A reprehenderit molestias repudiandae!",
//       },
//       {
//         descriptionHeader: "Other details",
//         descriptionContents:
//           "6.1 OLED, Dual Rear Camera, 6GB RAM, Apple A15 Bionic, 5G 4K / 30 fps, 3 x 31 minutes, 249 g HyperSmooth 5.0 Image Stabilization, 8x Slow-Motion Video GPS, NFC, Bluetooth 5.0, WiFi, up to 22 days (with solar power) HyperSmooth 5.0 Image Stabilization, 8x Slow-Motion Video 6.1 OLED, Dual Rear Camera, 6GB RAM, Apple A15 Bionic, 5G HyperSmooth 5.0 Image Stabilization, 8x Slow-Motion Video",
//       },
//       {
//         descriptionHeader: "Shipping",
//         descriptionContents:
//           "Fast shipping available for this product. Estimated delivery time is 3-5 business days.",
//       },
//       {
//         descriptionHeader: "Return policy",
//         descriptionContents:
//           "We accept returns within 30 days of purchase. Please contact us if you have any issues with your order.",
//       },
//       {
//         descriptionHeader: "Seller information",
//         descriptionContents:
//           "Best Deals Electronics is a trusted seller with a 98% positive feedback rating. Contact us for any inquiries about this product.",
//       },
//     ],
//   },
//   {
//     id: 20,
//     name: "Quality Loafers",
//     amount: 15600,
//     originalAmount: 5000,
//     category: "Phones",
//     brandName: "Android",
//     slug: "Quality-Loafers-20",
//     images: [
//       "/images/product1.png",
//       "/images/product2.png",
//       "/images/orderImage.png",
//       "/images/product5.png",
//     ],
//     seller: "Glamour Shoes Store",
//     count: 1,
//     quantity: 10,
//     productDetails: [
//       {
//         descriptionHeader: "Product description",
//         descriptionContents:
//           "High-quality leather loafers for a comfortable and stylish look. Available in various sizes and colors.",
//       },
//       {
//         descriptionHeader: "Other details",
//         descriptionContents:
//           "Genuine leather, non-slip sole, comfortable fit, suitable for both formal and casual occasions.",
//       },
//       {
//         descriptionHeader: "Shipping",
//         descriptionContents:
//           "Free shipping on all orders. Estimated delivery time is 5-7 business days.",
//       },
//       {
//         descriptionHeader: "Return policy",
//         descriptionContents:
//           "We offer a 30-day return policy. If you're not satisfied with your purchase, you can return it for a full refund.",
//       },
//       {
//         descriptionHeader: "Seller information",
//         descriptionContents:
//           "Glamour Shoes Store is your go-to destination for high-quality footwear. Contact us for any questions or special requests.",
//       },
//     ],
//   },
//   // ... (other products using the same format)
// ];
